#!/bin/sh

# This scrip copies the library in $FOAM_USER/lib, the application in
# $FOAM_USER/applications and the tutorial in $FOAM_USER/run

# If folders already exist a warning message will be showed
#mkdir $FOAM_RUN/
mkdir $FOAM_RUN/../applications

cp -r ../electrochemicalFoam $FOAM_RUN/../applications

cd $FOAM_RUN/../applications
wmake electrochemicalFoam
