#!/bin/sh
#cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cleanCase
rm -R 0
rm -R processor*
mkdir 0
cp -R 0.org/* 0/

runApplication blockMesh
#runApplication decomposePar
runApplication `getApplication` 
#runParallel `getApplication` 2
#runApplication reconstructPar
foamToVTK
#rm -R processor*

# ----------------------------------------------------------------- end-of-file
