#!/bin/sh
#cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cp -R system/pisoFoam/* system/

mkdir 0
cp -R constant/polyMesh/blockMeshDict.Initial constant/polyMesh/blockMeshDict
runApplication blockMesh

runApplication snappyHexMesh -overwrite

#- For non-parallel running
cp -R 0.org/* 0/ > /dev/null 2>&1
runApplication decomposePar

#- For parallel running
#ls -d processor* | xargs -i rm -rf ./{}/0 $1
#ls -d processor* | xargs -i cp -r 0.org ./{}/0 $1

#cp system/topoSetDict.fixedJump system/topoSetDict
runParallel topoSet 4
#runParallel createPatch 4 -overwrite
runParallel createBaffles 4 -overwrite
runParallel patchSummary 4 -expand


#runParallel `getApplication` 4
#runApplication reconstructPar

# ----------------------------------------------------------------- end-of-file
