#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake $makeType diffusivityModels 
wmake $makeType extendedReactionThermo 
wmake $makeType extendedChemistryModels 
wmake $makeType extendedBoundaryConditions 
wmake $makeType extendedTransportModels 
wmake $makeType electrochemistryModels 

# ----------------------------------------------------------------- end-of-file
