#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake $targetType extendedReactionThermo 
wmake $targetType extendedBoundaryConditions 
wmake $targetType electrochemistryModels 

# ----------------------------------------------------------------------------
